/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IAgent, IAgentInterface } from "../IAgent";

const _abi = [
  {
    inputs: [],
    name: "canExec",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "exec",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAgent__factory {
  static readonly abi = _abi;
  static createInterface(): IAgentInterface {
    return new Interface(_abi) as IAgentInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IAgent {
    return new Contract(address, _abi, runner) as unknown as IAgent;
  }
}
