/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAgent } from "./IAgent";
export * as factories from "./factories";
export { IAgent__factory } from "./factories/IAgent__factory";
